export const CHANGE_INPUT_VALUE_CATEGORY_TITLE = 'CHANGE_INPUT_VALUE_CATEGORY_TITLE';
export const ADD_CATEGORY_ITEM 				   = 'ADD_CATEGORY_ITEM';
export const DELETE_CATEGORY_ITEM			   = 'DELETE_CATEGORY_ITEM';
export const CHANGE_CATEGORY_TEXT 			   = 'CHANGE_CATEGORY_TEXT';
export const SUBMIT_CATEGORY_INPUT			   = 'SUBMIT_CATEGORY_INPUT';
export const CHANGE_INPUT_CATEGORY_ITEM		   = 'CHANGE_INPUT_CATEGORY_ITEM';
export const ADD_SUBCATEGORY_ITEM			   = 'ADD_SUBCATEGORY_ITEM';
export const GENERATION_LEVEL_CATEGORY		   = 'GENERATION_LEVEL_CATEGORY';
export const CHANGE_CHECKED_CATEGORY		   = 'CHANGE_CHECKED_CATEGORY';
export const HANDLE_CHECKED_TASK			   = 'HANDLE_CHECKED_TASK';


export const CHANGE_SHOW_MODAL 				   = 'CHANGE_SHOW_MODAL';
export const CHANGE_TEXT_MODAL_TASK 		   = 'CHANGE_TEXT_MODAL_TASK';
export const CHANGE_IS_DONE_MODAL 			   = 'ISDONEMODAL';
export const CHANGE_INDEX_MODAL_CATEGORY 	   = 'CHANGE_INDEX_MODAL_CATEGORY';
export const CHANGE_INDEX_MODAL_TASK 		   = 'CHANGE_INDEX_MODAL_TASK';
export const CHANGE_TASK_MODAL_SELECTED 	   = 'CHANGE_TASK_MODAL_SELECTED';
export const CHANGE_DISABLED_TASK_INPUTS 	   = 'CHANGE_DISABLED_TASK_INPUTS';
export const CHANGE_TASK_IFON 				   = 'CHANGE_TASK_IFON';
export const CHANGE_CATEGORY_ITEMS 			   = 'CHANGE_CATEGORY_ITEMS';